export const DB_MOCK_CENTERS = [
  {
    id: 1,
    shortName: "club campestre",
    longName: "club campestre",
    image: "club-campestre.png",
    address: "Avenida 68 N34, salon 3",
    schedule: "L - V, 8:00 am - 9:00 pm",
    places: 12,
    availableSchedules: "12/08/2024",
  },
  {
    id: 2,
    shortName: "centro de bienestar",
    longName: "centro de bienestar sede salitre",
    image: "cb-salitre.png",
    address: "Avenida 128 N34, salon 3",
    schedule: "L - V, 8:00 am - 9:00 pm",
    places: 30,
    availableSchedules: "12/08/2024",
  },
  {
    id: 3,
    shortName: "club madelena",
    longName: "club madelena",
    image: "club-madelena.jpeg",
    address: "Avenida Cali N34, salon 3",
    schedule: "L - V, 8:00 am - 9:00 pm",
    places: 3,
    availableSchedules: "12/08/2024",
  },
  {
    id: 4,
    shortName: "colégio cafam",
    longName: "Colégio CAFAM",
    image: "colegio-cafam.png",
    address: "Calle 60 N34, salon 3",
    schedule: "L - V, 8:00 am - 9:00 pm",
    places: 20,
    availableSchedules: "12/08/2024",
  },
];
